version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: myadminsecretkey #add hasura admin_secret here
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
